services:
  api:
    image: ghcr.io/${GITHUB_REPOSITORY}:${IMAGE_TAG}
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.marhaen.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.marhaen.entrypoints=https"
      - "traefik.http.routers.marhaen.tls=true"
      - "traefik.http.routers.marhaen.service=marhaen"
      - "traefik.http.services.marhaen.loadbalancer.server.port=${PORT}"
    environment:
      - PORT=${PORT}
      - APP_NAME=${APP_NAME}
      - APP_REVISION=${APP_REVISION}
      - NODE_ENV=${APP_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - FE_URL=${FE_URL}
      - BE_URL=${BE_URL}
      - EMAIL_USERNAME=${EMAIL_USERNAME}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - MIDTRANS_SERVER_KEY=${MIDTRANS_SERVER_KEY}
      - MIDTRANS_CLIENT_KEY=${MIDTRANS_CLIENT_KEY}
      - PAYMENT_GATEWAY_ENABLED=${PAYMENT_GATEWAY_ENABLED}
      - QRIS_MITRA_URL=${QRIS_MITRA_URL}
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true
