name: 🚀 CI/CD Development

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Development

    steps:
      - name: 📦 Checkout Code
        uses: actions/checkout@v4

      - name: 🧰 Setup Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📥 Install Dependencies
        run: npm install

      - name: 🔐 Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: 🛠️ Build Docker Image
        run: docker build -t nevmock/marhaen-api-dev:latest .

      - name: 📤 Push Docker Image
        run: docker push nevmock/marhaen-api-dev:latest

      - name: 🚢 Deploy to VPS Server
        uses: appleboy/ssh-action@master
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          BE_URL: ${{ secrets.BE_URL }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          MIDTRANS_SERVER_KEY: ${{ secrets.MIDTRANS_SERVER_KEY }}
          MIDTRANS_CLIENT_KEY: ${{ secrets.MIDTRANS_CLIENT_KEY }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
          IV_SECRET: ${{ secrets.IV_SECRET }}
          PORT: ${{ secrets.PORT }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🔁 Pulling latest Docker image..."
            docker pull nevmock/marhaen-api-dev:latest

            echo "🛑 Stopping and removing old container (if exists)..."
            docker stop marhaen-api-dev || true
            docker rm marhaen-api-dev || true

            echo "🚀 Running new container..."
            docker run -d \
              --name marhaen-api-dev \
              --network dev-postgresql-network \
              --restart unless-stopped \
              -e PORT=3000 \
              -e DATABASE_URL="$DATABASE_URL" \
              -e BE_URL="$BE_URL" \
              -e EMAIL_USERNAME="$EMAIL_USERNAME" \
              -e EMAIL_PASSWORD="$EMAIL_PASSWORD" \
              -e JWT_SECRET="$JWT_SECRET" \
              -e MIDTRANS_SERVER_KEY="$MIDTRANS_SERVER_KEY" \
              -e MIDTRANS_CLIENT_KEY="$MIDTRANS_CLIENT_KEY" \
              -e ENCRYPTION_KEY="$ENCRYPTION_KEY" \
              -e IV_SECRET="$IV_SECRET" \
              -p "$PORT":3000 \
              nevmock/marhaen-api-dev:latest

            echo "🧹 Cleaning up unused Docker resources..."
            docker system prune -f
            
            echo "✅ Deployment to Development environment completed successfully!"